# Generated by Django 4.1.7 on 2023-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(default='image.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time_spent',
            field=models.FloatField(),
        ),
    ]
